# Generated by Django 5.2 on 2025-07-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeProductDim',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('update_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_product_dim',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDim',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('update_date', models.DateField(auto_now=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.coffeeproductdim')),
            ],
            options={
                'db_table': 'ledger_employee_dim',
            },
        ),
        migrations.CreateModel(
            name='CoffeeTransactionSummary',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.employeedim')),
            ],
            options={
                'db_table': 'ledger_transaction_summary',
            },
        ),
        migrations.CreateModel(
            name='CoffeeTransactionDetail',
            fields=[
                ('transaction_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_date', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.coffeeproductdim')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.coffeetransactionsummary')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='ledger.employeedim')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ledger.employeedim')),
            ],
            options={
                'db_table': 'ledger_transaction_detail',
            },
        ),
        migrations.CreateModel(
            name='CoffeeGeneralLedgerBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('update_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.employeedim')),
            ],
            options={
                'db_table': 'ledger_general_ledger_balances',
            },
        ),
    ]
