# Generated by Django 5.2 on 2025-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_coffeetransactiondetail_debtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedim',
            name='current_employee',
            field=models.BooleanField(default=True),
        ),
    ]
