# Generated by Django 5.2 on 2025-07-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_employeedim_current_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetransactiondetail',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='ledger.employeedim'),
        ),
        migrations.AlterField(
            model_name='coffeetransactiondetail',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ledger.employeedim'),
        ),
        migrations.AlterField(
            model_name='coffeetransactionsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.employeedim'),
        ),
    ]
