name: Deploy Django Backend to Azure

on:
  push:
    branches:
      - dev-deployment

env:
  AZURE_WEBAPP_NAME: bean-counter
  PYTHON_VERSION: '3.13'
  DJANGO_PROJECT_DIR: 'beancounter/backend'    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: ${{ env.DJANGO_PROJECT_DIR }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      working-directory: ${{ env.DJANGO_PROJECT_DIR }}
      run: python manage.py migrate

    - name: Collect static files
      working-directory: ${{ env.DJANGO_PROJECT_DIR }}
      run: python manage.py collectstatic --noinput

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.DJANGO_PROJECT_DIR }}
