name: Deploy Django Backend to Azure Web App

on:
  push:
    branches:
      - dev-deployment
      

env:
  AZURE_WEBAPP_NAME: bean-counter
  AZURE_WEBAPP_PACKAGE_PATH: backend
  PYTHON_VERSION: 3.13

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Django migrations
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          python manage.py migrate --noinput
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

