name: Deploy Django App to Azure Web App

on:
  push:
    branches:
      - dev-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Create startup script
        working-directory: ./backend
        run: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          echo "Running migrations..."
          python manage.py migrate
          echo "Starting gunicorn..."
          gunicorn --bind 0.0.0.0:8000 --timeout 600 config.wsgi:application
          EOF
          chmod +x startup.sh
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend
          
      - name: Configure Azure App Settings
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --settings \
                DB_NAME="${{ secrets.DB_NAME }}" \
                DB_USER="${{ secrets.DB_USER }}" \
                DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                DB_HOST="${{ secrets.DB_HOST }}" \
                DB_PORT="${{ secrets.DB_PORT }}" \
                ALLOWED_ORIGINS="${{ secrets.ALLOWED_ORIGINS }}" \
                ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" \
                SCM_DO_BUILD_DURING_DEPLOYMENT=1
                
            az webapp config set \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --startup-file "startup.sh"