name: Deploy Django App to Azure Web App

on:
  push:
    branches:
      - dev-deployment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create startup script
        working-directory: ./backend
        run: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Collecting static files..."
          python manage.py collectstatic --noinput
          echo "Running migrations..."
          python manage.py migrate
          echo "Starting gunicorn..."
          gunicorn --bind 0.0.0.0:8000 --timeout 600 config.wsgi:application
          EOF
          chmod +x startup.sh
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend